export const projects = [
    {
        id: 1,
        title: 'Morent Car Rental',
        subtitle: 'A car rental website',
        description: 'SITE DESCRIPTION',
        stack: [
            'React + hooks',
            'React Router',
            'React Helmet',
            'React Skeleton',
            'React Context',
            'SCSS',
            'Axios',
            'css-shortcut',
        ],
        image: '/images/projects/cover-1.png',
        demo: 'https://react-vite-rent.vercel.app/cars',
        github: 'https://github.com/bondarkoff/react-vite-rent',
        isReact: true,
    },
    {
        id: 2,
        title: 'Marvel Information Portal',
        subtitle: 'A Marvel universe information portal',
        description: 'SITE DESCRIPTION',
        stack: [
            'React + hooks',
            'React Router',
            'React Helmet',
            'React Skeleton',
            'Prop-Types',
            'SCSS',
        ],
        image: '/images/projects/cover-2.png',
        demo: 'https://react-vite-rent.vercel.app/cars',
        github: 'https://github.com/bondarkoff/react-vite-rent',
        isReact: true,
    },
    {
        id: 3,
        title: 'React Sneakers',
        subtitle: 'A sneakers online store',
        description: 'SITE DESCRIPTION',
        stack: [
            'React + hooks',
            'React Router',
            'React Context',
            'React Skeleton',
            'Axios',
            'SCSS',
            'Macro-css',
        ],
        image: '/images/projects/cover-3.png',
        demo: 'https://react-vite-rent.vercel.app/cars',
        github: 'https://github.com/bondarkoff/react-vite-rent',
        isReact: true,
    },
    {
        id: 4,
        title: 'Website Portfolio',
        subtitle: 'My own old portfolio',
        description: 'SITE DESCRIPTION',
        stack: ['JavaScript', 'SCSS', 'Gulp'],
        image: '/images/projects/cover-4.png',
        demo: 'https://react-vite-rent.vercel.app/cars',
        github: 'https://github.com/bondarkoff/react-vite-rent',
        isReact: false,
    },
];

export default function handler(req, res) {
    res.status(200).json(projects);
}
